/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DonateAlertRouteImport } from './routes/donate-alert'
import { Route as MatchHistoryRouteImport } from './routes/match-history'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as ApiMatchesRouteImport } from './routes/api/matches'
import { Route as ApiMmrRouteImport } from './routes/api/mmr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateAlertRoute = DonateAlertRouteImport.update({
  id: '/donate-alert',
  path: '/donate-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchHistoryRoute = MatchHistoryRouteImport.update({
  id: '/match-history',
  path: '/match-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesRoute = ApiMatchesRouteImport.update({
  id: '/api/matches',
  path: '/api/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMmrRoute = ApiMmrRouteImport.update({
  id: '/api/mmr',
  path: '/api/mmr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate-alert': typeof DonateAlertRoute
  '/match-history': typeof MatchHistoryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/support': typeof SupportRoute
  '/tracker': typeof TrackerRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/mmr': typeof ApiMmrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate-alert': typeof DonateAlertRoute
  '/match-history': typeof MatchHistoryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/support': typeof SupportRoute
  '/tracker': typeof TrackerRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/mmr': typeof ApiMmrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate-alert': typeof DonateAlertRoute
  '/match-history': typeof MatchHistoryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/support': typeof SupportRoute
  '/tracker': typeof TrackerRoute
  '/api/matches': typeof ApiMatchesRoute
  '/api/mmr': typeof ApiMmrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donate-alert'
    | '/match-history'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/support'
    | '/tracker'
    | '/api/matches'
    | '/api/mmr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate-alert'
    | '/match-history'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/support'
    | '/tracker'
    | '/api/matches'
    | '/api/mmr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donate-alert'
    | '/match-history'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/support'
    | '/tracker'
    | '/api/matches'
    | '/api/mmr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonateAlertRoute: typeof DonateAlertRoute
  MatchHistoryRoute: typeof MatchHistoryRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SupportRoute: typeof SupportRoute
  TrackerRoute: typeof TrackerRoute
  ApiMatchesRoute: typeof ApiMatchesRoute
  ApiMmrRoute: typeof ApiMmrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate-alert': {
      id: '/donate-alert'
      path: '/donate-alert'
      fullPath: '/donate-alert'
      preLoaderRoute: typeof DonateAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-history': {
      id: '/match-history'
      path: '/match-history'
      fullPath: '/match-history'
      preLoaderRoute: typeof MatchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches': {
      id: '/api/matches'
      path: '/api/matches'
      fullPath: '/api/matches'
      preLoaderRoute: typeof ApiMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mmr': {
      id: '/api/mmr'
      path: '/api/mmr'
      fullPath: '/api/mmr'
      preLoaderRoute: typeof ApiMmrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonateAlertRoute: DonateAlertRoute,
  MatchHistoryRoute: MatchHistoryRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SupportRoute: SupportRoute,
  TrackerRoute: TrackerRoute,
  ApiMatchesRoute: ApiMatchesRoute,
  ApiMmrRoute: ApiMmrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
